export interface DictInterface<T> {
    [index: string]: T,
}

export interface PoolDataInterface {
    reference_asset: 'USD' | 'EUR' | 'BTC' | 'ETH' | 'LINK' | 'CRYPTO',
    N_COINS: number,
    underlying_decimals: number[],
    decimals: number[],
    tethered?: boolean[],
    use_lending: boolean[],
    is_plain: boolean[],
    has_eth?: boolean,
    is_aave?: boolean,
    is_new_underlying?: boolean,
    old_swap_address?: string,
    swap_address: string,
    token_address: string,
    gauge_address: string,
    old_token_address?: string,
    migration_address?: string,
    deposit_address?: string,
    underlying_coins: string[],
    coins: string[],
    underlying_coin_addresses: string[],
    coin_addresses: string[],
    swap_abi: any,
    deposit_abi?: any,
    old_swap_abi?: any,
    is_meta?: boolean,
    is_fake?: boolean,
    is_crypto?: boolean,
    meta_N?: number,
    meta_decimals?: number[],
    meta_coin_decimals?: number[],
    meta_wrapped_decimals?: number[],
    base_pool?: string,
    meta_coin_addresses?: string[],
    all_coin_addresses?: string[],
    is_factory?: boolean,
    adapter_abi?: any,
    old_adapter_address?: string,
    adapter_biconomy_address?: string,
    adapter_address?: string,
    migration_abi?: any,
    sCurveRewards_abi?: any,
    sCurveRewards_address?: string,
    aRewards_abi?: any,
    aRewards_address?: string,
    reward_token?: string,
    reward_tokens?: string[],
    pool_type?: string,
}