name: test.yml
on:
  push:

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint
      - run: npx hardhat node --fork ${{ secrets.ETH_RPC }} &
      - run: npm test
        env:
          ETH_RPC: ${{ secrets.ETH_RPC }}
